#pragma once

enum ADJUSTMD {
	ADJMD_NONE,
	ADJMD_NORMAL,
	ADJMD_NORMAL_S,
	ADJMD_SLOW,
	ADJMD_SLOW_S,
	ADJMD_TIME,
	ADJMD_THREE1,
	ADJMD_THREE1C,
	ADJMD_THREE2,
	ADJMD_THREE2C,
	ADJMD_THREE3,
	ADJMD_THREE3C,
	ADJMD_THREE4,
	ADJMD_THREE4C,
	ADJMD_THREE5,
	ADJMD_THREE5C,
	ADJMD_RELATIVE1,
	ADJMD_RELATIVE1C,
	ADJMD_RELATIVE2,
	ADJMD_RELATIVE2C,
	ADJMD_RELATIVE3,
	ADJMD_RELATIVE3C,
	ADJMD_RELATIVE4,
	ADJMD_RELATIVE4C,
	ADJMD_RELATIVE5,
	ADJMD_RELATIVE5C,
	ADJMD_RELATIVE6,
	ADJMD_FORFREECAM
};

enum DIRECTMD {
	DIRECTMD_SONIC,
	DIRECTMD_UNKNOWN,
	DIRECTMD_TARGET
};